//
// Created by etienne on 27/04/2022.
//

#ifndef CARCASSONNE_LO21_P22_JOUEURRESSOURCES_H
#define CARCASSONNE_LO21_P22_JOUEURRESSOURCES_H


class JoueurRessources {

};


#endif //CARCASSONNE_LO21_P22_JOUEURRESSOURCES_H
